
package ñ;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ayar
 */
public class GUI_Subcons extends javax.swing.JFrame {

    /**
     * Creates new form ramParents
     */
    public GUI_Subcons() {
        initComponents();
    }

    /**
     * Establecer los valores de la tabla de conjunciones, seleccionar las
     * conjunciones padres de la ramificación seleccionada.
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listModelAllSubconjunctions = new DefaultListModel();
        ñl_AllSubconjunctions = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        ñb_ConsReset = new javax.swing.JButton();
        ñb_ConsOk = new javax.swing.JButton();
        ñb_ConsCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conjunciones contradiccionales");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de conjunciones"));

        ñl_AllSubconjunctions.setModel(listModelAllSubconjunctions);
        jScrollPane2.setViewportView(ñl_AllSubconjunctions);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html>Presione la tecla <i>Ctrl</i> para seleccionar y deseleccionar las conjunciones. Escoja aquellas de las cuales desciende la ramificacióñ.</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ñb_ConsReset.setText("Reestablecer");
        ñb_ConsReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ñb_ConsResetActionPerformed(evt);
            }
        });

        ñb_ConsOk.setText("Aceptar");
        ñb_ConsOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ñb_ConsOkActionPerformed(evt);
            }
        });

        ñb_ConsCancel.setText("Cancelar");
        ñb_ConsCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ñb_ConsCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(ñb_ConsReset))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(ñb_ConsOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ñb_ConsCancel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ñb_ConsOk)
                    .addComponent(ñb_ConsCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ñb_ConsReset)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ñb_ConsOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ñb_ConsOkActionPerformed
        // Si alguna conjunción seleccionada en ñl_Cons pertenece a la
        // disyunción seleccionada en ñl_Ram, informar del error y regresar
        for(int i : ñl_AllSubconjunctions.getSelectedIndices()){
            if (i/3 == GUI.ñl_Ram.getSelectedIndex()){
                JOptionPane.showMessageDialog(rootPane, "La(s) conjuncion(es) "
                        + "seleccionada(s) pertenece(n) a la misma disyunción, \n"
                        + "pero una disyunción no puede descender de si misma.",
                        "Error de selección",
                        JOptionPane.INFORMATION_MESSAGE);
//                allOk=false;
                return;
            }
        }
        
        // Si la selección está bien, establecer los padres de la disyunción.
        // Ñ hace la conversión entre int[] y ArrayList<Integer>
        Ñ.setParentsIndices(Ñ.amuyaña.getDisjunctions().get(GUI.ñl_Ram.getSelectedIndex()),
                ñl_AllSubconjunctions.getSelectedIndices());
        super.dispose();

        // recargar la lista de padres en ñl_RamFrom
        GUI.listModelRamParents.clear();
        for(String s : Ñ.getParentsNames(Ñ.amuyaña.getDisjunctions().get(GUI.ñl_Ram.getSelectedIndex()))){
            GUI.listModelRamParents.addElement(s);
        }
    }//GEN-LAST:event_ñb_ConsOkActionPerformed

    private void ñb_ConsResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ñb_ConsResetActionPerformed
    ñl_AllSubconjunctions.setSelectedIndices(Ñ.getParentsIndices
        (Ñ.amuyaña.getDisjunctions().get(GUI.ñl_Ram.getSelectedIndex())));
    }//GEN-LAST:event_ñb_ConsResetActionPerformed

    private void ñb_ConsCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ñb_ConsCancelActionPerformed
        super.dispose();

    }//GEN-LAST:event_ñb_ConsCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Subcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Subcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Subcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Subcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Subcons().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ñb_ConsCancel;
    private javax.swing.JButton ñb_ConsOk;
    private javax.swing.JButton ñb_ConsReset;
    protected static javax.swing.JList<String> ñl_AllSubconjunctions;
    protected static DefaultListModel<String> listModelAllSubconjunctions;
    // End of variables declaration//GEN-END:variables
}
